pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') { 
            steps {
                sh './jenkins/scripts/test.sh' 
            }
        }
         stage('Push to nexus') {
            steps {
              // withCredentials([string(credentialsId: 'NPM_TOKEN_ID', variable: 'NPM_TOKEN')]) {
              //   sh 'npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}' // Or your private registry URL
              //   sh 'npm install'
              
              //    }
              sh '''
                                VERSION=$(node -p "require('./package.json').version")
 
                                if [[ "$VERSION" == *"-SNAPSHOT"* ]]; then
                                  echo "Deploying snapshot to Nexus snapshot repository..."
                                  npm publish --registry=$(node -p "require('./package.json').publishConfig.registry")
                                else
                                  echo "Deploying release to Nexus release repository..."
                                  npm publish --registry=$(node -p "require('./package.json').releasePublishConfig.registry")
                                fi
                           
                '''
            }
        }
    }
}
